name: 기능 제안
description: 다음에 추가할 기능을 제안해 주세요.
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 해결하려는 문제
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 제안하는 동작
    validations:
      required: true
